### ISSUE TITLE
Phones show as Bad Format

### ISSUE THREAD

**Issue by szeke** [NextCenturyCorporation/dig-ui#2]
All the phones are showing as **Bad Format**, sounds like the KG is not agreeing with Thomas' assumptions. They have the following format:
```
"phone": [
        {
          "confidence": 1000,
          "provenance": [
          ],
          "key": "xxxxxxxxxx",
          "value": "xxxxxxxxxx"
```

What should the keys look like?

**Comment by rartiss55** [comment]
Logged in JIRA as DIG-1183.

**Comment by rartiss55** [comment]
looks like an issue with the type set in the config -- closing.
