### ISSUE TITLE
Displayed description is not correct

### ISSUE THREAD

**Issue by saggu** [NextCenturyCorporation/dig-ui#3]
For eg, in this page: http://10.3.2.82:8090/offer.html?id=90F918B2E9111F9685C61ED9FFD6CE1C7F847980FE72FB21588FB493008D449D

The description in `indexed` is the correct one, looks like DIG GUI is displaying description from `content_strict` still.

This gives an impression that either readability or more importantly, inferlink rules are not working

**Comment by saggu** [comment]
Another example - http://10.3.2.82:8090/offer.html?id=2B3947809D2537AC27DE4B2A9600A1BD63FE38635D489C9E9B00828FEAA9D3BE

**Comment by ThomasSchellenbergNextCentury** [comment]
Should be working now, though I think the links you posted are broken since you switched the index alias.
